[package]
name = "some-mut"
description = "A utility library for deferring the take()ing of an Option"
version = "0.1.2"
edition = "2021"
repository = "https://github.com/coolreader18/some-mut"
license = "MIT"
